#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成正确的getpath.h文件"""

import os
import marshal

def generate_getpath_h():
    """生成正确的getpath.h文件"""
    
    # 获取Python源码目录
    python_src_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "Python-3.12.2")
    getpath_py_file = os.path.join(python_src_dir, "Modules", "getpath.py")
    getpath_h_file = os.path.join(python_src_dir, "Python", "frozen_modules", "getpath.h")
    
    print("============================================================")
    print("生成正确的getpath.h文件")
    print("============================================================")
    
    # 检查输入文件是否存在
    if not os.path.exists(getpath_py_file):
        print(f"❌ 输入文件不存在: {getpath_py_file}")
        return False
    
    # 读取getpath.py文件内容
    with open(getpath_py_file, 'rb') as f:
        text = f.read()
    
    print(f"✅ 已读取getpath.py文件，大小: {len(text)} 字节")
    
    # 编译并marshal代码
    filename = "<frozen getpath>"
    code = compile(text, filename, "exec", optimize=0, dont_inherit=True)
    marshalled = marshal.dumps(code)
    
    print(f"✅ 已编译并marshal代码，大小: {len(marshalled)} 字节")
    
    # 生成头文件
    header = "/* Auto-generated by generate_getpath_h.py */"
    arrayname = "_Py_M__getpath"
    data_size = len(marshalled)
    
    # 确保输出目录存在
    os.makedirs(os.path.dirname(getpath_h_file), exist_ok=True)
    
    with open(getpath_h_file, 'w', encoding='utf-8') as outfile:
        outfile.write(header)
        outfile.write("\n")
        outfile.write(f"const unsigned char {arrayname}[] = {{\n")
        
        # 写入数据
        for n in range(0, data_size, 16):
            outfile.write("    ")
            outfile.write(",".join(str(i) for i in marshalled[n : n + 16]))
            outfile.write(",\n")
        
        outfile.write("};\n")
    
    print(f"✅ 已生成getpath.h文件: {getpath_h_file}")
    
    # 验证生成的文件
    with open(getpath_h_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if arrayname in content and "const unsigned char" in content:
        print("✅ 文件验证成功")
        print(f"文件大小: {len(content)} 字符")
        print(f"包含数组: {arrayname}")
    else:
        print("❌ 文件验证失败")
        return False
    
    return True

if __name__ == "__main__":
    generate_getpath_h()