#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
生成真正的deepfreeze.c文件
这个文件应该包含所有冻结模块的符号定义
"""

import os

def generate_deepfreeze_c():
    """生成真正的deepfreeze.c文件"""
    
    # Python源码目录
    python_src_dir = r"e:\GitHub3\cpp\BPython\src\Python-3.12.2"
    frozen_modules_dir = os.path.join(python_src_dir, "Python", "frozen_modules")
    deepfreeze_dir = os.path.join(python_src_dir, "Python", "deepfreeze")
    
    # 冻结模块头文件列表
    frozen_headers = [
        "importlib__bootstrap.h",
        "importlib__bootstrap_external.h", 
        "zipimport.h",
        "abc.h",
        "codecs.h",
        "io.h",
        "_collections_abc.h",
        "getpath.h"
    ]
    
    # 生成deepfreeze.c内容
    deepfreeze_content = '''/*
 * Deepfreeze modules
 * 
 * This file is auto-generated by deepfreeze.py
 * It contains the deep-frozen modules for Python.
 */

#include "Python.h"

'''
    
    # 添加头文件包含
    for header in frozen_headers:
        deepfreeze_content += f'#include "frozen_modules/{header}"\n'
    
    deepfreeze_content += '''
/* Deepfreeze module definitions */

'''
    
    # 添加模块定义
    modules = [
        ("importlib._bootstrap", "importlib__bootstrap"),
        ("importlib._bootstrap_external", "importlib__bootstrap_external"),
        ("zipimport", "zipimport"),
        ("abc", "abc"),
        ("codecs", "codecs"),
        ("io", "io"),
        ("_collections_abc", "_collections_abc"),
        ("getpath", "getpath")
    ]
    
    # 添加模块数组定义
    deepfreeze_content += '''static const struct _frozen _PyImport_FrozenModules[] = {
'''
    
    for module_name, header_name in modules:
        deepfreeze_content += f'    {{ "{module_name}", _Py_M_{header_name}, (int)sizeof(_Py_M_{header_name}) }},\n'
    
    deepfreeze_content += '''    {0, 0, 0} /* sentinel */
};

'''
    
    # 添加初始化函数
    deepfreeze_content += '''/* Deepfreeze initialization function */
void _Py_Deepfreeze_Init(void) {
    /* Initialize frozen modules */
    PyImport_FrozenModules = _PyImport_FrozenModules;
}

void _Py_Deepfreeze_Fini(void) {
    /* Cleanup frozen modules */
    PyImport_FrozenModules = NULL;
}
'''
    
    # 写入deepfreeze.c文件
    deepfreeze_file = os.path.join(deepfreeze_dir, "deepfreeze.c")
    with open(deepfreeze_file, 'w', encoding='utf-8') as f:
        f.write(deepfreeze_content)
    
    print(f"✅ 已生成真正的deepfreeze.c文件: {deepfreeze_file}")
    
    # 验证文件内容
    with open(deepfreeze_file, 'r', encoding='utf-8') as f:
        content = f.read()
        print(f"文件大小: {len(content)} 字符")
        print(f"包含模块数量: {len(modules)}")

if __name__ == "__main__":
    generate_deepfreeze_c()